# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('a_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
