# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='a_value',
        ),
        migrations.RemoveField(
            model_name='site',
            name='b_value',
        ),
        migrations.AddField(
            model_name='sitestats',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_stats', to='stats.Site'),
        ),
    ]
