# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170330_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitestats',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
